version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: library-postgres
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: libraryuser
      POSTGRES_PASSWORD: Ubizor21
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - library-network

  backend:
    build:
      context: /var/www/library-app/backend
    container_name: library-backend
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: library
      DB_USER: libraryuser
      DB_PASSWORD: Ubizor21
      PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - library-network

  frontend:
    build:
      context: /var/www/library-app/frontend
    container_name: library-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - library-network

volumes:
  postgres_data:

networks:
  library-network:
    driver: bridge
