---
- name: Create VM in Yandex Cloud
  hosts: localhost
  connection: local
  vars:
    yc_token: "y0__xCh8NLnBRjB3RMg5eCaphRnFYGG5mq8vact1_EEIzJjaL-3yQ"
    yc_cloud_id: "b1g0m7dlds35t25mqpvc"
    yc_folder_id: "b1ghuulab94793d4h4eq"
    
  tasks:
    - name: Create VM
      uri:
        url: "https://compute.api.cloud.yandex.net/compute/v1/instances"
        method: POST
        headers:
          Authorization: "Bearer {{ yc_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          folderId: "{{ yc_folder_id }}"
          name: "library-app-vm-ansible"
          zoneId: "ru-central1-a"
          platformId: "standard-v2"
          resourcesSpec:
            memory: "2147483648"
            cores: "2"
          bootDiskSpec:
            diskSpec:
              size: "21474836480"
              imageId: "fd8kdq6d0p8sij7h5qe3"
          networkInterfaceSpecs:
            - subnetId: "e9bieunfbfdi9o7qdl8m"
              primaryV4AddressSpec:
                oneToOneNatSpec:
                  ipVersion: "IPV4"
          metadata:
            user-data: |
              #cloud-config
              users:
                - name: ubuntu
                  groups: sudo
                  shell: /bin/bash
                  sudo: ['ALL=(ALL) NOPASSWD:ALL']
                  ssh-authorized-keys:
                    - {{ lookup('file', '~/.ssh/id_rsa.pub') }}
        status_code: 200
      register: vm_result

    - name: Show VM creation result
      debug:
        var: vm_result
